import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, DatePicker, Space, version } from "antd";
import AppointmentCard from '../components/Cards/AppointmentCard';
import Procedures from '../components/Procedures/Procedures';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Define Cosmetic Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="App">
          <AppointmentCard></AppointmentCard>
          <Procedures/>
        </div>
      </main>
    </div>
  )
}

export default Home
