import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, DatePicker, Space, version } from "antd";
import AppointmentCard from '../components/Cards/AppointmentCard';
import Procedures from '../components/Procedures/Procedures';
import About from '../components/About/About';

const Home: NextPage = () => {
  return (
    <div id={'container'}>
      <Head>
        <title>Define Cosmetic Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'main'}>
        <div className="App">
          <AppointmentCard></AppointmentCard>
          <Procedures/>
          <About/>
        </div>
      </main>
    </div>
  )
}

export default Home
